### ISSUE TITLE
Split comparison sorts from other sorting algorithms

### ISSUE THREAD

**Issue by jube** [josem/bigoref#2]
It would be nice to split [comparison sorts](http://en.wikipedia.org/wiki/Comparison_sort) from other sorting algorithms. Because putting the `n log(n)` complexity in orange is misleading as it's the best possible complexity for a comparison sorts. It should clearly be green. Splitting (and maybe explaining the difference) could clarify this problem.

**Comment by josem** [comment]
Hi @jube! :)

Sorry for my delay here, for some reason I missed the notification of the issue. 

The reason I put that in orange is because n \* log(n) is kind of an ok complexity (best one for many algorithms) but relatively not as good as O(n) which is green and not as bad as O(n^2) which is in red so I tried to create a visual representation of how expensive it is to run different algorithms.

I hope that makes sense! But yeah, I should probably be more clear with that.
